---
- name: 'copy the file'
  hosts : dev_server
  remote_user: test
  tasks:
    - name: 'coping the file'
      copy:
        src: target/test-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        dest: /home/ubuntu/
        
        

     